READ_FILE = "../res/read.jpg"
WRITE_FILE = "../res/write.jpg"
READ_FILE_MD = "../res/read_md.jpg"
READ_FILE_MD_2 = "../res/read_md_2.jpg"
WRITE_FILE_MD = "../res/write_md.jpg"
WHITE_SPACE_FILE_MD = "../res/write md.jpg"

TEST_READ_TAG_1 = "My Dummy Tag öä ' \" "
TEST_READ_TAG_2 = "tag 2"
TEST_READ_TAG_3 = "tag 3"
TEST_READ_VALUE_FIELD = "Some string with 'ä' and \"quotes"

TEST_WRITE_TAG_1 = "My other Dummy Tag öä ' \" "
TEST_WRITE_TAG_2 = "tag 2"

QUERY_FILE_1 = "../res/query_1.jpg"
QUERY_FILE_2 = "../res/query_2.jpg"
QUERY_FILE_3 = "../res/query_3.jpg"
QUERY_FILE_4 = "../res/query_4.jpg"
QUERY_TAG_1 = "Tag 1"
QUERY_TAG_2 = "Tag 2"
QUERY_TAG_3 = "Tag 3"
QUERY_TAG_4 = "Tag 4"
